name: Build and publish container

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Why ?'
        required: false
        default: ''

jobs:
  ghr_push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Log-in to ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login https://ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push container image
        run: |
          IMAGE_ID=ghcr.io/coldwings/photon-ut-base
          # Strip git ref prefix from version
          VERSION=latest
          # Build and Publish container image
          docker buildx build --push \
          --tag $IMAGE_ID:$VERSION \
          --platform linux/amd64,linux/arm64 .
